// ─── KANAR QUILL ARCHIVES: WORLD HISTORY LORE ENTRIES ────────────────────────
// Extracted from 135 newsletters (2006-2025) spanning in-game years ~998–1025 TM.
// Organized chronologically by publication era with full search metadata.

interface LoreSeedEntry {
  title: string;
  content: string;
  summary: string;
  source: string;
  year: number;
  month: number;
  locations: string;   // JSON array
  characters: string;  // JSON array
  tags: string;        // JSON array
  category: "story" | "announcement" | "recap" | "obituary" | "rumor";
}

export const loreSeedEntries: LoreSeedEntry[] = [

  // ═══════════════════════════════════════════════════════════════════════════════
  // ERA 1: THE TOMMARIN WARS & EARLY HISTORY (~995–997 TM)
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "Heroes of the Tommarin Wars (995–997)",
    content: `Twenty-five years ago, the Tommarin Empire occupied the Princedom of Novashan. Six heroes from Ilvaresh rose to end the occupation and liberate their homeland.\n\nDuke Sir Mythindor Wanderlust, founder of House Chaos and master swordsman, was field-knighted by Prince Duncan Belthshazzar. He became Duke of Anadar and later died defending Wynderfel against the Stormlord's horde — his body was claimed by a dragon.\n\nBaron G'nip G'nop, Second Lord of House Jhereg, sacrificed his wealth to bring down the Empire and served twice as Mayor of Ilvaresh.\n\nCaptain Daryth Calishman of the Blackhawk mercenaries was a skilled scout and spy, presumed dead after the war.\n\nJanus Shadowhand of House Chaos, the legendary trap master, was torn apart by the Iron Golem of Turan Ghek.\n\nMagister Alexander Cross, co-founder of the Crescent Order of Mages, served a Death Knight for a year to obtain an artifact needed to defeat the vampire Marcus Tenebron.\n\nLady Deedlit, an elven druidess and 17th Blackhawk member, fled the Orb Chamber before it imploded and destroyed the Tommarin capital. She later died defending Upper Anadarrian forest from the Sapphire Awakening.`,
    summary: "The six heroes of Ilvaresh who ended the Tommarin Empire's occupation of Novashan: Mythindor, G'nip G'nop, Daryth, Janus, Alexander Cross, and Lady Deedlit.",
    source: "Mystic Quill - May 1021",
    year: 2021, month: 5,
    locations: JSON.stringify(["Ilvaresh", "Novashan", "Anadar", "Wynderfel", "Turan Ghek"]),
    characters: JSON.stringify(["Duke Sir Mythindor Wanderlust", "Baron G'nip G'nop", "Captain Daryth Calishman", "Janus Shadowhand", "Magister Alexander Cross", "Lady Deedlit", "Prince Duncan Belthshazzar", "Marcus Tenebron"]),
    tags: JSON.stringify(["tommarin", "war", "heroes", "history", "liberation", "house-chaos"]),
    category: "story",
  },
  {
    title: "Kieran Leonthas and the Elven Extermination Plot",
    content: `In the earliest days of Novashani history, the elven noble Kieran Leonthas orchestrated a secret plot to exterminate humanity. The conspiracy was uncovered when coded messages were intercepted at Theotwig Mage University.\n\nThe revelation led to the formation of House Chaos under Vandal Bloodflame, and a series of vampiric killings shook the realm as dark forces exploited the chaos. The fallout from Leonthas's conspiracy shaped human-elven relations for generations, creating a deep undercurrent of distrust that persists to this day.`,
    summary: "Ancient elven conspiracy to exterminate humanity, uncovered at Theotwig Mage University. Led to formation of House Chaos.",
    source: "Mystic Quill - October 2011",
    year: 2011, month: 10,
    locations: JSON.stringify(["Theotwig Mage University", "Novashan"]),
    characters: JSON.stringify(["Kieran Leonthas", "Vandal Bloodflame"]),
    tags: JSON.stringify(["elves", "conspiracy", "history", "house-chaos", "vampires"]),
    category: "story",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ERA 2: XANDRICK'S REBELLION & THE STORMLORD (~998–1008 TM)
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "Sir Xandrick's Manifesto Against the Nobility",
    content: `Sir Xandrick Dimitri von Olanov has published a declaration of war against the nobility of Novashan. In a fiery manifesto distributed throughout the Princedom, Xandrick denounces corruption and injustice among the ruling class.\n\nHe specifically names Duke Kieran D'Kalin, Baroness Felicity Ashenwood, Lord Aeracon Whiteoak, Lord G'nip G'nop, Sir Dar'Khan the Corrupted, and Sir Raleigh the Craven as targets of his ire.\n\nMost dramatically, Xandrick has renounced his station as Knight of the Thistle and taken the title "Knight of the Broken Arrow and Warden of Winterfell," formally breaking from the established order. He is now declared an Enemy of the Princedom.`,
    summary: "Knight Xandrick von Olanov declares war on Novashan's corrupt nobility, renounces his knighthood, and takes Winterfell as his base.",
    source: "Novashan Quill - October 998",
    year: 2006, month: 10,
    locations: JSON.stringify(["Winterfell", "Novashan"]),
    characters: JSON.stringify(["Sir Xandrick von Olanov", "Duke Kieran D'Kalin", "Baroness Felicity Ashenwood", "Lord Aeracon Whiteoak", "Lord G'nip G'nop"]),
    tags: JSON.stringify(["rebellion", "politics", "xandrick", "knighthood", "manifesto"]),
    category: "story",
  },
  {
    title: "The Ghotakra Orc Split",
    content: `The Ghotakra orc tribe has splintered into two factions under the leadership of Ba'Hawkeen. The orc known as the Candle Maker was beaten by townsfolk of Dunn Creek, highlighting the ongoing tensions between human settlements and orc communities.\n\nThe death of Ba'Zagdula precipitated the internal conflict. Meanwhile, Tomarrian mage Zephran Chandler was captured and beaten by townsfolk with the involvement of Allen Hawkins and an unnamed elven leader — showing that anti-outsider violence runs deep in the borderlands.`,
    summary: "Ghotakra orcs split into factions under Ba'Hawkeen. Human-orc tensions escalate with beatings in Dunn Creek.",
    source: "Novashan Quill - November 998",
    year: 2006, month: 11,
    locations: JSON.stringify(["Dunn Creek", "Ghotakra Territory"]),
    characters: JSON.stringify(["Ba'Hawkeen", "Ba'Zagdula", "Candle Maker", "Zephran Chandler", "Allen Hawkins"]),
    tags: JSON.stringify(["orcs", "faction", "violence", "racial-tension"]),
    category: "story",
  },
  {
    title: "Blue Ring Trading Company Founded",
    content: `Brunwolf Deepanvil has announced the founding of the Blue Ring Trading Company, a new mercantile venture seeking to dominate trade throughout Novashan. The company quickly establishes itself along the Heron's Way trade route.\n\nWhile initially welcomed as a sign of economic growth, the Blue Ring Trading Company would later come to be seen as an economic menace by local merchants, using its growing influence to corner markets and squeeze out competition.`,
    summary: "Brunwolf Deepanvil founds the Blue Ring Trading Company. Initially welcomed, it later becomes an economic threat.",
    source: "Novashan Quill - June 998",
    year: 2006, month: 6,
    locations: JSON.stringify(["Novashan", "Heron's Way"]),
    characters: JSON.stringify(["Brunwolf Deepanvil"]),
    tags: JSON.stringify(["trade", "economy", "merchant", "guild"]),
    category: "announcement",
  },
  {
    title: "Post-Stormlord Recovery: Spring Brings Rebirth",
    content: `After the devastating conflict with Stormlord Stormholm, Novashan begins its recovery. Trade revives between Novashan, Nardmyrr, and Wyndover. However, threats remain on every front.\n\nXandrick and his Broken Arrow faction lurk in Winterfell. Undead haunt the Cursed Forest in southern Autruche. Tensions simmer in Fennor. The Cro-Kindre orc group probes the borders.\n\nStrange creatures appear across the land as magical energies from the Stormlord's fall continue to ripple through the countryside. Adventurers are in high demand as the Prince works to rebuild the shattered Princedom.`,
    summary: "Post-Stormlord recovery. Trade revives but threats remain: Xandrick's rebels, undead, orc incursions, and strange creatures.",
    source: "Novashan Quill - May 1008",
    year: 2007, month: 10,
    locations: JSON.stringify(["Novashan", "Nardmyrr", "Wyndover", "Winterfell", "Autruche", "Fennor"]),
    characters: JSON.stringify(["Xandrick", "Stormlord Stormholm"]),
    tags: JSON.stringify(["recovery", "stormlord", "aftermath", "threats"]),
    category: "recap",
  },
  {
    title: "Orcs Seek Acceptance: Brug Grorbag's Acts of Chivalry",
    content: `Four orcs led by Brug Grorbag have been traveling Novashan performing acts of chivalry, trying to prove that orcs can be honorable. They wear a green dragon crest and have been sighted helping travelers, defending caravans, and even rescuing a merchant's daughter from bandits.\n\nMeanwhile, the Broken Bone tribe led by Hamdaga One Hand approaches Ilverash peacefully but is met with hostility. The tribe is confused about Ilverash's unfriendliness despite their peaceful intentions.\n\nThe debate over orc integration continues to divide Novashan's communities.`,
    summary: "Brug Grorbag's orc band performs knightly deeds. Broken Bone tribe seeks peace with Ilverash but is rejected. Orc integration debated.",
    source: "Novashan Quill - May 1008",
    year: 2007, month: 10,
    locations: JSON.stringify(["Novashan", "Ilverash"]),
    characters: JSON.stringify(["Brug Grorbag", "Hamdaga One Hand"]),
    tags: JSON.stringify(["orcs", "chivalry", "integration", "diplomacy", "racism"]),
    category: "story",
  },
  {
    title: "Bayomal Forest Grows Supernaturally",
    content: `The forest at the Bayomal Divide has been growing at an unnatural rate. Trees spring up overnight. Paths shift and change. Soldiers get lost for days.\n\nFey activity is strongly suspected. Silver Bow clan scouts report being guided by nature spirits within the forest, while others report hostile encounters with magical creatures.\n\nThe Bayomal Forest would continue to grow and change for years, becoming one of Novashan's most mysterious and dangerous regions — a living barrier between the civilized lands and something older and stranger.`,
    summary: "The Bayomal Forest grows supernaturally overnight. Fey involvement suspected. Nature spirits guide some travelers while the forest traps others.",
    source: "Novashan Quill - April 1009",
    year: 2009, month: 4,
    locations: JSON.stringify(["Bayomal Divide", "Bayomal Forest"]),
    characters: JSON.stringify(["Silver Bow Clan"]),
    tags: JSON.stringify(["fey", "forest", "magic", "supernatural", "mystery"]),
    category: "story",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ERA 2b: THE IRON CRISIS & UNDEAD THREAT (~1008–1009 TM)
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "Wyndover Sacked by Undead Legion",
    content: `The city of Wyndover has been devastated by an attack from an undead legion. The creatures swept in from the darkness, overwhelming the city's defenses.\n\nSymon Copper-Mantle, trusted advisor to Prince Duncan, coordinates the defense but the city suffers catastrophic damage. Homes are crushed under catapult stones. Bodies litter the streets.\n\nThough the flag of the Barony still flies over the ruins, Wyndover lies in shambles. Repairs begin on the northern quarter, the most heavily damaged area, but the city will take years to fully recover.`,
    summary: "Undead legion sacks Wyndover. Massive casualties and destruction. Advisor Symon Copper-Mantle coordinates defense.",
    source: "Mystic Quill - February 1008",
    year: 2008, month: 2,
    locations: JSON.stringify(["Wyndover"]),
    characters: JSON.stringify(["Symon Copper-Mantle", "Prince Duncan"]),
    tags: JSON.stringify(["undead", "siege", "destruction", "wyndover"]),
    category: "story",
  },
  {
    title: "The Black Scar Mine Crisis",
    content: `The Black Scar iron mine in Taradyr has been attacked by unknown forces. Miners are fleeing in terror. The Miners Guild has pulled all workers from Taradyr, halting iron production entirely.\n\nScouting parties sent into the mines never returned. Dwarven tunnel-crawlers dispatched to investigate also disappeared. All contact with the mine is lost.\n\nWith iron caravans also being intercepted and weapons shipments vanishing, Novashan faces an economic and military crisis. Three caravans carrying weapons from Taradyr smithies have vanished without a trace. The iron shortage threatens the Princedom's ability to arm its defenders.`,
    summary: "Black Scar mine attacked, miners flee, scouts vanish inside. Iron production halted. Weapons caravans disappearing. Military crisis.",
    source: "Mystic Quill - February 1008",
    year: 2008, month: 2,
    locations: JSON.stringify(["Black Scar Mine", "Taradyr"]),
    characters: JSON.stringify(["Miners Guild"]),
    tags: JSON.stringify(["mines", "iron", "crisis", "economy", "mystery", "dwarves"]),
    category: "story",
  },
  {
    title: "Winterfell Freed: Xandrick's Redemption",
    content: `In one of the most dramatic events in recent memory, Duke Mythindor's body has been freed from necromantic control at Winterfell.\n\nDame Felicity Ashenwood led a group to Winterfell to confront Sir Xandrick, who despite his outlaw status, proved he kept his wits to the end. Using the Staff of the Green Witch, Xandrick broke the necromancy binding Mythindor's corpse. The remains of seven Thistle Armsmen were also recovered.\n\nXandrick's act of redemption — freeing the very hero whose body he was accused of desecrating — has complicated the Princedom's stance toward the exiled knight. Though still officially an outlaw, many now view him with grudging respect.`,
    summary: "Xandrick uses the Staff of the Green Witch to free Duke Mythindor's body from necromancy at Winterfell. A controversial act of redemption.",
    source: "Novashan Quill - June 1008",
    year: 2008, month: 6,
    locations: JSON.stringify(["Winterfell", "Yardsmuth"]),
    characters: JSON.stringify(["Sir Xandrick von Olanov", "Duke Mythindor Wanderlust", "Dame Felicity Ashenwood"]),
    tags: JSON.stringify(["necromancy", "redemption", "xandrick", "mythindor", "winterfell"]),
    category: "story",
  },
  {
    title: "Sir Metrion the Ebon Lion Kills Coppernantle",
    content: `Wyndover suffers another devastating undead attack, this time led by the terrifying Sir Metrion the Ebon Lion, a death knight of terrible power.\n\nSymon Copper-Mantle, the Prince's trusted advisor, is killed in the assault. Lannister forces garrison the area in the aftermath, but the loss of Coppernantle is a severe blow to Prince Duncan's inner circle.\n\nThe death knight's continued attacks on Wyndover suggest the undead threat is far more organized and purposeful than initially feared.`,
    summary: "Death Knight Sir Metrion attacks Wyndover again. Prince Duncan's advisor Symon Copper-Mantle is killed.",
    source: "Mystic Quill - March 2009",
    year: 2009, month: 3,
    locations: JSON.stringify(["Wyndover"]),
    characters: JSON.stringify(["Sir Metrion the Ebon Lion", "Symon Copper-Mantle", "Prince Duncan", "Count Lorras Lannister"]),
    tags: JSON.stringify(["undead", "death-knight", "assassination", "wyndover"]),
    category: "obituary",
  },
  {
    title: "Pelain Mine Collapse: 31 Dead",
    content: `The mine in Pelain has suffered a catastrophic collapse. Initial reports put the death toll at 23, but as rescue efforts by Johanson's Delvers continue, the count rises to 31.\n\nD'Galie's mining operation is devastated, but the operator vows to continue. The tragedy comes at the worst possible time, with iron already scarce due to the Black Scar mine crisis in Taradyr.\n\nThe collapse raises questions about mining safety standards and whether the push to extract more iron to replace lost Taradyr production led to corners being cut.`,
    summary: "Catastrophic mine collapse in Pelain kills 31. D'Galie vows to continue. Questions about safety standards amid iron crisis.",
    source: "Mystic Quill - May 1009",
    year: 2009, month: 5,
    locations: JSON.stringify(["Pelain"]),
    characters: JSON.stringify(["D'Galie", "Johanson's Delvers"]),
    tags: JSON.stringify(["mines", "disaster", "death", "pelain", "iron"]),
    category: "story",
  },
  {
    title: "Prince Duncan Marries Lady Iyleina; Heir Born",
    content: `Prince Duncan Belthshazzar has married Lady Iyleina Radveshi. The royal couple toured the northern regions, including the former elven lands, and met the barbarian leader Bearskinner.\n\nOn May 28, 1009 TM, an heir is born: Prince Daffyd Alekzander Belthshazzar. The birth in Baern is celebrated across the Princedom, though some whisper about the child's sandy hair, unusual among the dark-haired Belthshazzar line.\n\nThe succession seems secure — but the future would reveal that appearances can be deceiving.`,
    summary: "Prince Duncan marries Lady Iyleina. Prince Daffyd born in Baern on May 28, 1009. Questions about the heir's appearance.",
    source: "Mystic Quill - June 1009",
    year: 2009, month: 6,
    locations: JSON.stringify(["Baern", "Novashan"]),
    characters: JSON.stringify(["Prince Duncan Belthshazzar", "Lady Iyleina Radveshi", "Prince Daffyd Belthshazzar", "Bearskinner"]),
    tags: JSON.stringify(["royalty", "wedding", "heir", "succession", "birth"]),
    category: "story",
  },
  {
    title: "BeastLord Bearskinner Claims Lands of Novashan",
    content: `The barbarian leader known as BeastLord Bearskinner has begun building a town called Hammerhalt near the Barony of Tarridear. A bridge is under construction over the River Yengeth.\n\nIn a shocking development, Baron Thordrun, the dwarven Baron of Tarridear, has publicly joined Bearskinner's cause. An embrace between the two leaders was witnessed. Dwarven engineers now help construct the bridge.\n\nThis represents a direct challenge to the Princedom's authority and a major political defection. With the iron crisis and undead threats already stretching Novashan thin, the barbarian expansion may go unchecked.`,
    summary: "Barbarian leader Bearskinner builds Hammerhalt, claims Novashan territory. Dwarven Baron Thordrun defects to his cause.",
    source: "Mystic Quill - May/June 1009",
    year: 2009, month: 6,
    locations: JSON.stringify(["Hammerhalt", "Tarridear", "River Yengeth"]),
    characters: JSON.stringify(["BeastLord Bearskinner", "Baron Thordrun"]),
    tags: JSON.stringify(["barbarians", "expansion", "defection", "dwarves", "politics"]),
    category: "story",
  },
  {
    title: "Major Political Reorganization of Novashan",
    content: `Sweeping political changes reshape the Princedom:\n\nLord Sir William Drakensburg becomes Regent. Sir Gustov Canter is elevated to Duke. Duke D'Kalin is freed from his duties.\n\nThe Order of the Scepter is created as a new knightly order, while the Order of the Thistle becomes the Princedom's official Knightly Order.\n\nFelicity Ashenwood is elevated from Baroness to Countess. Count Gilbert Rosentretor takes the County of Shadowglade.\n\nThese changes represent Prince Duncan's effort to consolidate power and reward loyal supporters while removing those who failed during the Stormlord crisis.`,
    summary: "Major government reshuffling: new Regent, Duke, and Countess. New knightly orders created. Power consolidated under loyal supporters.",
    source: "Mystic Quill - June 1009",
    year: 2009, month: 6,
    locations: JSON.stringify(["Yardsmuth", "Shadowglade", "Novashan"]),
    characters: JSON.stringify(["Lord Sir William Drakensburg", "Sir Gustov Canter", "Duke D'Kalin", "Countess Felicity Ashenwood", "Count Gilbert Rosentretor"]),
    tags: JSON.stringify(["politics", "nobility", "reorganization", "knighthood"]),
    category: "announcement",
  },
  {
    title: "Norsica Born Anew: Grimstadd Founded",
    content: `After the fall of the Stormlord, the Norsican people begin rebuilding their homeland. Ryclin Baerson of the Stag Clan reports that multiple clans — including Stag and Gull — are unifying to rebuild.\n\nThe first settlement is Grimstadd, established on the old Norsican coast. Years of slavery under Stormholm's regime have hardened these people, and they are determined never to be conquered again.\n\nHiemdal Throst, a freed Norsican prisoner, recounts being liberated by mysterious warriors bearing a mark across the eye — an unknown faction whose identity remains a mystery.`,
    summary: "Norsicans rebuild after Stormlord's fall. First settlement Grimstadd founded. Mysterious warriors helped free Norsican prisoners.",
    source: "Mystic Quill - June 1009",
    year: 2009, month: 6,
    locations: JSON.stringify(["Norsica", "Grimstadd"]),
    characters: JSON.stringify(["Ryclin Baerson", "Hiemdal Throst"]),
    tags: JSON.stringify(["norsica", "rebuilding", "freedom", "settlement"]),
    category: "story",
  },
  {
    title: "Human-Dwarf Tensions Erupt: Grain Silo Arson in Arakelian",
    content: `Five dwarven arsonists have burned grain silos in the town of Arakelian in Tarridear, killing three watch members and dozens of others.\n\nSir Kyle Wrothschild accuses the dwarven Baron of Tarridear of extorting humans and ordering the grain burned. The dwarves burned the silos themselves when their demands went unmet, killing twelve or more people.\n\nSir Kyle vows to withhold taxes until a proper accounting is provided. The incident represents a critical breakdown in human-dwarf relations and threatens to plunge Tarridear into open conflict.`,
    summary: "Dwarven arsonists burn grain silos in Arakelian, killing dozens. Sir Kyle accuses the Baron. Human-dwarf relations collapse.",
    source: "Mystic Quill - July 1009",
    year: 2009, month: 7,
    locations: JSON.stringify(["Arakelian", "Tarridear"]),
    characters: JSON.stringify(["Sir Kyle Wrothschild", "Baron Thordrun"]),
    tags: JSON.stringify(["arson", "dwarves", "conflict", "tarridear", "grain"]),
    category: "story",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ERA 3: THE SHADOW WAR (~1010–1011 TM)
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "The Shadow War Begins",
    content: `Forces in black and gold — the Shadowborn — have conquered Nightbourne, Yarik, Brenn, and much of the Principality in a devastating surprise campaign.\n\nGeneral Shavaras Y'sar commands the Shadow's military forces with ruthless efficiency. Duke Cantor, Duke D'Kalin, and Viscount D'Cather lead the desperate resistance.\n\nIn a sinister twist, several prominent heroes — Aria, Dravin, Gailin, Tarnahil, Greywolf, and Fenaric — are impersonated by Shadow agents. Aaron Gregory is later exposed as the betrayer who facilitated the deception.\n\nThe war plunges Novashan into its darkest hour since the Tommarin occupation.`,
    summary: "The Shadowborn conquer multiple cities. Key heroes impersonated. Aaron Gregory exposed as traitor. Novashan's darkest hour.",
    source: "Mystic Quill - 2010/2011",
    year: 2010, month: 5,
    locations: JSON.stringify(["Nightbourne", "Yarik", "Brenn", "Novashan"]),
    characters: JSON.stringify(["General Shavaras Y'sar", "Duke Cantor", "Duke D'Kalin", "Viscount D'Cather", "Aaron Gregory"]),
    tags: JSON.stringify(["shadow-war", "invasion", "betrayal", "shadowborn"]),
    category: "story",
  },
  {
    title: "Massacre at Willow Farmstead",
    content: `Reports detail a horrific massacre at Willow Farmstead. The violence against civilians marks a new low in the ongoing conflicts plaguing the Principality.\n\nThe massacre is attributed to forces exploiting the chaos of the Shadow War. With the military stretched thin defending cities, rural farmsteads are left virtually unprotected.\n\nMaster Blackmantle makes a heroic last stand against overwhelming forces — his sacrifice buying time for some survivors to escape. The warrior's stand becomes legendary among the common folk.`,
    summary: "Civilians massacred at Willow Farmstead during Shadow War. Master Blackmantle's heroic last stand saves some survivors.",
    source: "Mystic Quill - May 1010",
    year: 2010, month: 5,
    locations: JSON.stringify(["Willow Farmstead"]),
    characters: JSON.stringify(["Master Blackmantle"]),
    tags: JSON.stringify(["massacre", "shadow-war", "heroism", "sacrifice"]),
    category: "story",
  },
  {
    title: "Shadow War: Yardsmuth Retaken, Allowen Relieved",
    content: `The tide of the Shadow War begins to turn. Yardsmuth is retaken by forces of the Order of the Thistle in a decisive battle.\n\nAllowen is relieved by a coalition of loyalist forces, including mysterious Pegasus riders who appear at a critical moment to turn the battle.\n\nSquire Leveer Silverleaf earns his knighthood through valor in the fighting. John Purveyor is summoned from the countryside to aid the defense. Riversfork is freed from Shadow control.\n\nRobin the Mad, a bandit leader, is subdued. Black Riders — elite Shadow cavalry — are defeated in a running battle through the forests. The legendary Dragon Meg is encountered near the front lines.`,
    summary: "Shadow War turns: Yardsmuth retaken, Allowen relieved. Pegasus riders appear. Squire Leveer knighted. Multiple victories.",
    source: "Mystic Quill - 2011",
    year: 2011, month: 6,
    locations: JSON.stringify(["Yardsmuth", "Allowen", "Riversfork"]),
    characters: JSON.stringify(["Squire Leveer Silverleaf", "John Purveyor", "Robin the Mad", "Dragon Meg"]),
    tags: JSON.stringify(["shadow-war", "liberation", "knighthood", "pegasus", "victory"]),
    category: "recap",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ERA 4: FAMINE, COLLAPSE & RENEWAL (~1012–1013 TM)
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "The Great Famine of Novashan",
    content: `Following the devastation of the Shadow War, widespread famine and drought grip Novashan. Trade collapses. Roads become dangerous.\n\nGhosts haunt the abandoned village of Haverton. Strange deaths occur across the countryside. In New Holtz, red creatures erupt from the ground.\n\nThe famine pushes many to desperation. Crime rises as hungry people turn to theft and banditry. The Principality's infrastructure, already battered by war, crumbles further.\n\nOnly druid magic offers hope — practitioners using Regrowth techniques eventually manage to nearly double crop yields, ending the famine by late 1013.`,
    summary: "Post-Shadow War famine devastates Novashan. Trade collapses, supernatural threats emerge, crime rises. Druid magic eventually saves crops.",
    source: "Mystic Quill - 2012",
    year: 2012, month: 5,
    locations: JSON.stringify(["Novashan", "Haverton", "New Holtz"]),
    characters: JSON.stringify([]),
    tags: JSON.stringify(["famine", "drought", "ghosts", "crisis", "druid-magic"]),
    category: "story",
  },
  {
    title: "Lady Berreth and the Rise of the Berrethian Order",
    content: `During the famine, a new religious figure emerges: Lady Berreth, whose Temple Sirinth becomes a beacon of hope. The Berrethian Order grows rapidly among the desperate populace.\n\nBut the order's growth attracts dark attention. The necromancer Gwydeon steals Berreth's body from Greenhill cemetery in a midnight raid, and a lich later attacks Ilvaresh itself.\n\nSir Laveer swears solemn oaths to protect the faithful and pursue the desecrators. The incident shakes public confidence in both the secular and religious authorities' ability to protect the people.`,
    summary: "Lady Berreth's religious order rises during the famine. Necromancer Gwydeon steals her body. Lich attacks Ilvaresh.",
    source: "Mystic Quill - 2012",
    year: 2012, month: 7,
    locations: JSON.stringify(["Temple Sirinth", "Greenhill", "Ilvaresh"]),
    characters: JSON.stringify(["Lady Berreth", "Necromancer Gwydeon", "Sir Laveer"]),
    tags: JSON.stringify(["religion", "necromancy", "lich", "temple", "desecration"]),
    category: "story",
  },
  {
    title: "Narrdmyr Falls: Duke Gilcrest's Coup",
    content: `The Kingdom of Narrdmyr is thrown into chaos. Duke Wilmont Gilcrest of Dynsforth has mounted a coup against King Vallend II.\n\nThe King, his wife the Queen, and their young children were captured in Blackshire while attending the funerals of Prince Kenneth and Lord Sigmund Gilcrest. The family of County Mishanter, riding from Scotia to attend, were ambushed on the road — their bodies hung from trees on the borders of Noch Tiron.\n\nA state of civil war now exists across Narrdmyr. When the Tomarrian army passed through on its way to invade the Daggoth Empire, they destroyed Castlemount and killed Duke Gregor, Prince Duncan's supporter and lord commander of the King's Army.`,
    summary: "Duke Gilcrest coups against King Vallend II of Narrdmyr. Royal family captured. Mishanter family massacred. Civil war erupts.",
    source: "Mystic Quill - August 1013",
    year: 2013, month: 8,
    locations: JSON.stringify(["Narrdmyr", "Blackshire", "Dynsforth", "Noch Tiron", "Scotia", "Castlemount"]),
    characters: JSON.stringify(["Duke Wilmont Gilcrest", "King Vallend II", "Prince Kenneth", "Lord Sigmund Gilcrest", "Duke Gregor", "Count Mishanter"]),
    tags: JSON.stringify(["coup", "narrdmyr", "civil-war", "royalty", "massacre"]),
    category: "story",
  },
  {
    title: "The Ravensworth Revelation: Daffyd's Questionable Lineage",
    content: `A man recorded as Lecivious Ravensworth was found dead in a home in Crossroads. A blind man delivered from Wyndover via Lenik, he died of natural causes at advanced age.\n\nHis journals, written in flowering script and hand-pressed braille, contain explosive revelations:\n\n"I have raised a bastard as my son... he will never wield the power of the Sword of Raven against the coming darkness of the Demon Lord Lareth."\n\n"Duncan's boy Daffyd is not his own son. Sandy haired, where all others are dark, sturdy when others are lanky and fine, he is surely not the line of his father."\n\nIf Lecivious was King Vallend I in hiding, these journals suggest Prince Daffyd is not of Duncan's bloodline — and a secret legitimate heir exists. The implications for the succession are staggering.`,
    summary: "BOMBSHELL: Dead man's journals suggest he was King Vallend I. Claims Daffyd is not Duncan's biological son. A secret heir may exist.",
    source: "Mystic Quill - November 1013",
    year: 2013, month: 11,
    locations: JSON.stringify(["Crossroads", "Wyndover", "Lenik"]),
    characters: JSON.stringify(["Lecivious Ravensworth", "King Vallend I", "Prince Daffyd", "Prince Duncan", "Demon Lord Lareth"]),
    tags: JSON.stringify(["succession", "secret", "lineage", "royalty", "revelation"]),
    category: "story",
  },
  {
    title: "Daffyd Ascends: 'Daffyd is Our King!'",
    content: `Despite the questions surrounding his lineage, Prince Daffyd ascends to the throne of Novashan. Count Rosentrotter is expected to be named Lord Commander at the Winter Feast.\n\nCaptain Maigan Hornswelter reports the Narrdmyrian navy lies at the bottom of the bay of Tarn. A dragon is rumored to rest in the flooded ruins.\n\nSir Morus Lextant, master of the Raven Knights, has died — Daffyd will name a new Knight Commander of the Thistle. Sir Darkhan may be offered command of the Order of the Arrow.\n\nThe false knight Gullen Armboldt is captured and beheaded by Sir Locksley MacNeil after his campaign of banditry across Brenn, Wyndover, and Gray Haven.`,
    summary: "Prince Daffyd becomes King despite lineage questions. Gullen Armboldt beheaded. New military appointments made.",
    source: "Mystic Quill - October 1013",
    year: 2013, month: 10,
    locations: JSON.stringify(["Novashan", "Tarn", "Brenn", "Gray Haven"]),
    characters: JSON.stringify(["King Daffyd", "Count Rosentrotter", "Sir Locksley MacNeil", "Gullen Armboldt", "Captain Maigan Hornswelter", "Sir Darkhan"]),
    tags: JSON.stringify(["coronation", "succession", "execution", "politics"]),
    category: "story",
  },
  {
    title: "Death Moon Orc Tribe Rises; Devil-Wolf Returns",
    content: `A new orc tribe called the Death Moon has appeared in Eppingwood. They offer surprising resistance to the Stormchildren remnants and have attacked guards along Graywater River.\n\nOther orc tribes flock to the Death Moon banner, seeking glory. These orcs shun undead and pursue any creatures recalled from the afterlife with particular fervor. They mark trees with their half-moon symbol.\n\nMeanwhile, in Ilvaresh, a dreaded foe returns: the Devil-Wolf. Standing seven feet tall with fur black as jet and eyes like angry gold, the beast descends on a standoff between extraplanar monsters, tearing a deep dwarf to shreds before leaping away.`,
    summary: "Death Moon orcs rise in Eppingwood, shunning undead. The Devil-Wolf — a 7-foot black beast — returns to terrorize Ilvaresh.",
    source: "Mystic Quill - November 1013",
    year: 2013, month: 11,
    locations: JSON.stringify(["Eppingwood", "Graywater River", "Ilvaresh"]),
    characters: JSON.stringify(["Death Moon Tribe", "Devil-Wolf"]),
    tags: JSON.stringify(["orcs", "monster", "devil-wolf", "supernatural"]),
    category: "story",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ERA 5: THE ARBAN & CRIMSON BROTHERHOOD (~1014–1017 TM)
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "Hallot Secured: Refugees and Dark Elves",
    content: `The town of Hallot had been overrun by scavengers and bandits, then invaded by an unknown power possibly led by a dark elf. Refugees from Erin entered the town with support from militia from Brenn and Crossroads.\n\nA dark elf traveler proved instrumental to defending Hallot when a plague from Erin struck survivors. The dark elf led messengers between Brenn and Crossroads, coordinating the defense.\n\nThe irony of a dark elf saving a town was not lost on the populace — adding another chapter to the ongoing debate about racial tolerance in the Princedom.`,
    summary: "Hallot overrun by bandits then secured with help from militia and a dark elf traveler. Refugees from Erin bring plague.",
    source: "Mystic Quill - March 1014",
    year: 2014, month: 3,
    locations: JSON.stringify(["Hallot", "Erin", "Brenn", "Crossroads"]),
    characters: JSON.stringify([]),
    tags: JSON.stringify(["refugees", "dark-elf", "plague", "defense"]),
    category: "story",
  },
  {
    title: "The Arban: Land for Those Who Fight",
    content: `The Arban offers land to those willing to fight in the Light Infantry Forward Army for five years. All able-bodied Men, Elves, Dwarves, Half-Ogres, and legal half-breeds are eligible.\n\nCompletion entitles a soldier to two acres of land, with arms and food provided during service. General Lord Protector Bear Temur, High Marshall of Ashan, oversees the program.\n\nValean D'Traylin serves as Illverash Post Commander, processing recruits. The program represents a massive military buildup — the Arban is clearly preparing for a major campaign, though against what enemy remains unclear.`,
    summary: "The Arban offers land grants for 5 years military service. Major military buildup under General Bear Temur.",
    source: "Mystic Quill - March 1014",
    year: 2014, month: 3,
    locations: JSON.stringify(["Ashan", "Illverash"]),
    characters: JSON.stringify(["General Lord Protector Bear Temur", "Valean D'Traylin"]),
    tags: JSON.stringify(["military", "arban", "land-grants", "recruitment"]),
    category: "announcement",
  },
  {
    title: "The Crimson Brotherhood Invasion Begins",
    content: `A new and terrifying threat emerges: the Crimson Brotherhood. Their forces sweep through Narrdmyr, taking Gwendale as their first conquest.\n\nNecromancer rumors surface alongside their advance. The Brotherhood uses fear and dark magic as weapons, turning captured territories into nightmarish strongholds.\n\nKing Bashshar of Narrdmyr initially dismisses the threat, declaring Baern "a loss" rather than committing forces to defend it. His miscalculation would prove costly as the Brotherhood continues to expand.`,
    summary: "The Crimson Brotherhood invades Narrdmyr. Gwendale falls first. Dark magic and necromancy mark their advance.",
    source: "Mystic Quill - April 2016",
    year: 2016, month: 4,
    locations: JSON.stringify(["Gwendale", "Narrdmyr", "Baern"]),
    characters: JSON.stringify(["King Bashshar"]),
    tags: JSON.stringify(["crimson-brotherhood", "invasion", "necromancy", "war"]),
    category: "story",
  },
  {
    title: "Kingdom of Peth Declares Sovereignty",
    content: `In a stunning political upheaval, Peth declares sovereignty from the Crown. The Duchy of Erin is overrun in the process, and the Kingdom of Peth emerges as a new independent power.\n\nThirteen wandering constellations appear in the sky — their movement unexplained. Duchess Sarah Kantrill returns to Blackshire to rally loyalist forces.\n\nThe appearance of the constellations is interpreted by astrologers as an omen of profound change. No natural explanation is offered, and the phenomenon remains one of the great mysteries of the age.`,
    summary: "Peth declares independence. Duchy of Erin overrun. Thirteen constellations shift in the sky — unexplained cosmic omen.",
    source: "Mystic Quill - June/July 2016",
    year: 2016, month: 7,
    locations: JSON.stringify(["Peth", "Erin", "Blackshire"]),
    characters: JSON.stringify(["Duchess Sarah Kantrill"]),
    tags: JSON.stringify(["independence", "peth", "constellations", "omen", "politics"]),
    category: "story",
  },
  {
    title: "Grey Thorn Under Siege: Gavin Mudpot Falls",
    content: `The settlement of Grey Thorn endures repeated orc sieges throughout 1016. Wave after wave of attackers test the settlement's defenses.\n\nGavin Mudpot dies defending Grey Thorn in the final major assault. His sacrifice allows the remaining defenders to hold until Sir Kal brings a relief force in the spring of 1017.\n\nThe sieges demonstrate that despite diplomatic efforts, orc hostility toward human settlements remains a fundamental threat that no amount of Brug Grorbag-style chivalry has resolved.`,
    summary: "Grey Thorn besieged by orcs throughout 1016. Gavin Mudpot dies in the defense. Sir Kal brings relief in spring 1017.",
    source: "Mystic Quill - November 2016",
    year: 2016, month: 11,
    locations: JSON.stringify(["Grey Thorn"]),
    characters: JSON.stringify(["Gavin Mudpot", "Sir Kal"]),
    tags: JSON.stringify(["siege", "orcs", "death", "defense", "heroism"]),
    category: "obituary",
  },
  {
    title: "King Daffyd I Proclaimed; Novashan Rebuilt",
    content: `Daffyd I Belthshazarr is formally proclaimed King of Novashan. New borders are drawn. A Town Watch is formed under Captain Korra Stonebrooke in IlVeresh.\n\nSir Kal relieves the besieged Grey Thorn. The Western Shield is stationed at Hawkshaven to guard the frontier. New Barons are named: Aeracon Whiteoak Morinar receives Meraki, and Xandric Von Olanov — the former rebel — is elevated to baron.\n\nA press censorship decree makes questioning King Daffyd treasonous. The Mystic Quill itself comes under pressure, raising concerns about free speech under the new regime.`,
    summary: "Daffyd crowned King. New barons named (including reformed rebel Xandrick). Press censorship decree issued.",
    source: "Mystic Quill - March/July 2017",
    year: 2017, month: 3,
    locations: JSON.stringify(["Novashan", "IlVeresh", "Grey Thorn", "Hawkshaven", "Meraki"]),
    characters: JSON.stringify(["King Daffyd I", "Korra Stonebrooke", "Aeracon Whiteoak Morinar", "Xandric Von Olanov", "Sir Kal"]),
    tags: JSON.stringify(["coronation", "politics", "censorship", "barons", "military"]),
    category: "announcement",
  },
  {
    title: "The Jade Isles Expedition",
    content: `An expedition to the mysterious Jade Isles reveals an exotic and dangerous land. The travelers encounter:\n\nDoryubo, the Dai-Tengu atop Mt. Hotaka who commands the karasu-tengu bird warriors. Mimi, a nekomata — a two-tailed demon cat. The Yuki Onna, a deadly snow spirit.\n\nEmperor Seiwa, claiming descent from the sun goddess Amaterasu, marches south against an orc infestation. The Jade Isles operate under completely different rules — elementals that are common in Novashan have vanished here.\n\nThe expedition's reports open a window into a world vastly different from the familiar kingdoms of the west.`,
    summary: "Expedition to the Jade Isles encounters tengu, demon cats, snow spirits, and Emperor Seiwa's war against orcs.",
    source: "Mystic Quill - November 2016 / March 2017",
    year: 2016, month: 11,
    locations: JSON.stringify(["Jade Isles", "Mt. Hotaka"]),
    characters: JSON.stringify(["Doryubo", "Emperor Seiwa", "Mimi", "Yuki Onna"]),
    tags: JSON.stringify(["exploration", "jade-isles", "tengu", "foreign-lands"]),
    category: "story",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ERA 6: THE CRIMSON WAR & ILVERESH MYSTERIES (~1018–1020 TM)
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "The Battle of Daggett and the Three Armies",
    content: `A massive battle between Kingdom Peth, the Crimson Brotherhood, and regional forces summoned by Duchy Dynforth. The defenders prevailed in a hard-fought victory.\n\nCrimson Brotherhood troops retreated to dwindling strongholds in County Erin. A magical device was reportedly destroyed single-handedly by a Novashani outland defender.\n\nDuchess Sarah thanked Kingdom Novashan and the Dwarves of Brenned Mountain for their assistance. The battle marked the beginning of the end for the Crimson Brotherhood, though the war would continue for several more months.\n\nNotably, the Duke of Scotia was absent from the final assault — an absence that would later cost him his life.`,
    summary: "Major coalition victory at Daggett. Crimson Brotherhood retreats to County Erin. Scotia's absence noted.",
    source: "Mystic Quill - December 1020",
    year: 2020, month: 12,
    locations: JSON.stringify(["Daggett", "County Erin", "Dynforth"]),
    characters: JSON.stringify(["Duchess Sarah", "Crimson Brotherhood"]),
    tags: JSON.stringify(["battle", "crimson-brotherhood", "peth", "coalition", "war"]),
    category: "recap",
  },
  {
    title: "The Vanishing of Ilveresh",
    content: `The town of Ilveresh has completely vanished. The area is now blank forest — no buildings, no roads, no sign that a town ever existed there.\n\nReporter Netti MacInnes is investigating. Theories abound: Was it attacked? Did something crash into it? Or did it vanish like Tarn — simply ceasing to exist?\n\nThe disappearance of an entire town sends shockwaves through the Barony. By 1022, a new Ilveresh would be established as a kingsland serving as a neutral festival ground, but the mystery of what happened to the original town was never fully explained.`,
    summary: "The entire town of Ilveresh vanishes overnight, replaced by blank forest. No explanation found. New town later established.",
    source: "Mystic Quill - December 1020",
    year: 2020, month: 12,
    locations: JSON.stringify(["Ilveresh", "Tarn"]),
    characters: JSON.stringify(["Netti MacInnes"]),
    tags: JSON.stringify(["mystery", "vanishing", "supernatural", "ilveresh"]),
    category: "story",
  },
  {
    title: "Execution of Duke Ian MacGregor of Scotia",
    content: `King William Belthshazzar has ordered the public execution of Duke Ian MacGregor of Scotia in Valvendenn.\n\nThe charge: desertion of the Crown during the Battle of the Three Armies in November 1020. Scotia had been absent from the final assault that broke the Pethian uprising and the Crimson Brotherhood.\n\nThe execution was carried out by beheading, just two days after the order — before word could reach Scotia. The swift justice was seen by many as unnecessarily harsh and politically motivated.\n\nThe execution would have profound consequences, eventually leading to Scotia's civil war and ultimate declaration of independence.`,
    summary: "Duke MacGregor of Scotia executed for desertion at the Battle of Three Armies. Swift execution seen as politically motivated.",
    source: "Mystic Quill - August 1022",
    year: 2022, month: 8,
    locations: JSON.stringify(["Valvendenn", "Scotia"]),
    characters: JSON.stringify(["King William Belthshazzar", "Duke Ian MacGregor"]),
    tags: JSON.stringify(["execution", "scotia", "politics", "desertion", "justice"]),
    category: "story",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ERA 6b: BARONY OF BELLANMO LIFE (~1020–1022 TM)
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "Grand Opening of the Stag and Hound Inn",
    content: `Master Durgan Oakhart and Sir Tralik Norwood have opened a new inn in Crossroads called the Stag and Hound. Discounted rooms and drinks are offered during the grand opening.\n\nThe inn quickly becomes a community gathering place. The hide of the legendary White Stag is acquired and displayed above the main hearth, drawing visitors from across the Barony.\n\nBluebird, a resident water elemental, provides entertainment for patrons — though the creature has been suffering from indigestion after too many patrons blew bubbles into it.`,
    summary: "Stag and Hound Inn opens in Crossroads under Durgan Oakhart and Sir Tralik. White Stag hide displayed. Water elemental in residence.",
    source: "Mystic Quill - December 1020",
    year: 2020, month: 12,
    locations: JSON.stringify(["Crossroads", "Stag and Hound Inn"]),
    characters: JSON.stringify(["Durgan Oakhart", "Sir Tralik Norwood", "Bluebird"]),
    tags: JSON.stringify(["inn", "commerce", "community", "crossroads"]),
    category: "announcement",
  },
  {
    title: "Temple Haven Under Construction",
    content: `A new temple is being built in an evergreen grove south of Hallot and east of Gray Haven. White oak and red maple beams support a stone arch facade with hand-carved oak doors bearing Temple heraldry.\n\nSir Tralik Norwood oversees construction, expected to be completed by spring. The temple will serve as a center of healing and worship for the southern Barony.\n\nTemple Haven would later be reorganized under Temple Master Parisa and First Patron Clarence Nahame, becoming one of the most important religious institutions in the region.`,
    summary: "New temple built between Hallot and Gray Haven. Sir Tralik Norwood oversees construction. Becomes a major religious center.",
    source: "Mystic Quill - December 1020",
    year: 2020, month: 12,
    locations: JSON.stringify(["Temple Haven", "Hallot", "Gray Haven"]),
    characters: JSON.stringify(["Sir Tralik Norwood"]),
    tags: JSON.stringify(["temple", "construction", "religion", "healing"]),
    category: "announcement",
  },
  {
    title: "Discovering Wyndover: Capital of Barony Ausdauer",
    content: `Wyndover, once a lawless trading post, has become the capital of Barony Ausdauer since 1017 when Baron Sir Xandrick von Olanov was granted the barony.\n\nLady Karigan D'Morkishky D'Kalin serves as Seneschal. The city hosts the annual Festival of Flowers in April to honor fallen soldiers. The former rebel knight Xandrick has transformed from outlaw to respected baron — one of the most remarkable political redemptions in Novashani history.\n\nThe city thrives as a center of trade and governance, its troubled past as a frontier post largely forgotten.`,
    summary: "Profile of Wyndover, capital of Barony Ausdauer under reformed rebel Baron Xandrick. Lady Karigan serves as Seneschal.",
    source: "Mystic Quill - April 1021",
    year: 2021, month: 4,
    locations: JSON.stringify(["Wyndover", "Ausdauer"]),
    characters: JSON.stringify(["Baron Sir Xandrick von Olanov", "Lady Karigan D'Morkishky D'Kalin"]),
    tags: JSON.stringify(["city-profile", "wyndover", "ausdauer", "xandrick", "politics"]),
    category: "story",
  },
  {
    title: "Discovering Crossroads: The Refugee Town That Grew",
    content: `Crossroads was founded as a refugee town between Fennor and Ilveresh. Countess Kali relocated her Baronial seat there, and it later became part of Barony Ausdauer.\n\nThe town is home to the Oasis inn, many retired adventurers, and the Vanari Quarter with its famous horse breeders. The annual Grand Horse Festival in June draws visitors from across the kingdom.\n\nThe Vanari, a traveling people known for their horsemanship and culture, have established a permanent quarter in the town — a rare achievement for a traditionally nomadic people.`,
    summary: "Profile of Crossroads: refugee town turned thriving city. Home to the Oasis inn, Vanari Quarter, and Grand Horse Festival.",
    source: "Mystic Quill - May 1021",
    year: 2021, month: 5,
    locations: JSON.stringify(["Crossroads", "Fennor", "Ilveresh", "Oasis Inn", "Vanari Quarter"]),
    characters: JSON.stringify(["Countess Kali"]),
    tags: JSON.stringify(["city-profile", "crossroads", "vanari", "horses", "community"]),
    category: "story",
  },
  {
    title: "Lizardfolk Raids Along the River",
    content: `Scout Elizabeth Canter of Wyndover reports blue-bellied lizardfolk bands along the river between Wyndover and Gray Haven. They raided two farms — livestock taken, farmers killed.\n\nThe lizardfolk are diving deep into the river, apparently searching for something beneath the waters. What they seek remains a mystery, but their aggressive behavior suggests it is of great importance to them.\n\nThis is the latest in a long history of lizardfolk encounters stretching back to 998, when a new breed was first spotted near Brenn. Their population and aggression have been steadily increasing.`,
    summary: "Blue-bellied lizardfolk raiding farms between Wyndover and Gray Haven. Diving into river searching for something unknown.",
    source: "Mystic Quill - April 1021",
    year: 2021, month: 4,
    locations: JSON.stringify(["Wyndover", "Gray Haven"]),
    characters: JSON.stringify(["Elizabeth Canter"]),
    tags: JSON.stringify(["lizardfolk", "raids", "monster", "mystery"]),
    category: "story",
  },
  {
    title: "Merfolk Invasion Repelled at Hawks Haven",
    content: `Three separate Merfolk armies attempted invasion of Hawks Haven via land and sea in one of the most unusual military engagements in recent memory.\n\nThe defenders included the Arban, Storm Children, and a militia of orc/half-orc refugees led by chieftain Long Braid. In a historic moment, elves and orcs fought alongside one another for the first time.\n\nThe merfolk were repelled, but the fact that sea creatures could mount a three-pronged amphibious assault raises disturbing questions about what force organized them and what they wanted on the surface.`,
    summary: "Three merfolk armies attack Hawks Haven. Elves and orcs fight together for the first time. Merfolk repelled.",
    source: "Mystic Quill - March 1022",
    year: 2022, month: 3,
    locations: JSON.stringify(["Hawks Haven"]),
    characters: JSON.stringify(["Chieftain Long Braid"]),
    tags: JSON.stringify(["merfolk", "invasion", "orcs", "elves", "unity", "battle"]),
    category: "story",
  },
  {
    title: "Baroness Karigan's Coronation in Ilveresh",
    content: `Baroness Karigan D'Morkishky D'Kalin announces her coronation celebration in Ilveresh on June 4, 1022.\n\nThe celebration includes yard sales, a formal coronation ceremony, fighter tournaments (polearm, dual swords, sword and shield, archery), arts tournament (theme: Elegance), cooking tournament (fruity desserts), and a gambling tournament (Euchre).\n\nThe event represents the formal recognition of Karigan's rise from Seneschal to Baroness — one of the few commoner-born women to achieve baronial rank in the Principality's history.`,
    summary: "Baroness Karigan's coronation celebration in Ilveresh. Tournaments, arts, cooking, and gambling competitions.",
    source: "Mystic Quill - May 1022",
    year: 2022, month: 5,
    locations: JSON.stringify(["Ilveresh", "Ausdauer"]),
    characters: JSON.stringify(["Baroness Karigan D'Morkishky D'Kalin"]),
    tags: JSON.stringify(["coronation", "tournament", "celebration", "politics"]),
    category: "announcement",
  },
  {
    title: "'G' vs. the Knighthood: Anonymous Critic's Campaign",
    content: `An anonymous writer signing only as "G" launches a multi-issue campaign against the knighthood in the Mystic Quill.\n\nG calls knights "pathetic" and "incompetent," accusing them of serving only their own egos. Sir Miloc Elderhart publicly offers to meet G to discuss grievances. They meet, but G writes a scathing follow-up, criticizing Countess Felicity for talking over Sir Miloc.\n\nBy August, G pivots from direct attacks to a more philosophical tone, encouraging people to be their own heroes. G signs off with "we're watching" — suggesting an organized movement behind the anonymous writer.\n\nThe identity of G is never revealed.`,
    summary: "Anonymous 'G' attacks the knighthood in the Quill. Meets Sir Miloc but remains unsatisfied. Identity never revealed.",
    source: "Mystic Quill - March to August 1022",
    year: 2022, month: 3,
    locations: JSON.stringify(["Ilveresh", "Crossroads"]),
    characters: JSON.stringify(["G", "Sir Miloc Elderhart", "Countess Felicity Ashenwood"]),
    tags: JSON.stringify(["politics", "knighthood", "criticism", "anonymous", "debate"]),
    category: "story",
  },
  {
    title: "Dame Vera Einhearst Killed in a Duel",
    content: `Dame Vera Einhearst, a Narrdmyran knight from Barony Wildmere, was killed in a duel south of Wyndover by a dwarf believed to be Sir Bordra Hart of Tarridear.\n\nThe dwarf had confiscated food from a merchant. Dame Vera challenged her. Sir Bordra killed Dame Vera with a thrown hatchet at the very start of the fight — a dishonorable killing that some called murder.\n\nSir Bordra was already implicated in the death of an innocent boy that caused rioting in Tarridear. The incident deepens the human-dwarf tensions that have plagued Tarridear for over a decade.`,
    summary: "Dame Vera killed in a duel by Sir Bordra Hart via thrown hatchet. Bordra already implicated in a boy's death. Tensions rise.",
    source: "Mystic Quill - August 1022",
    year: 2022, month: 8,
    locations: JSON.stringify(["Wyndover", "Tarridear", "Wildmere"]),
    characters: JSON.stringify(["Dame Vera Einhearst", "Sir Bordra Hart"]),
    tags: JSON.stringify(["duel", "death", "dwarves", "honor", "tarridear"]),
    category: "obituary",
  },
  {
    title: "Children Become Violent Across Novashan",
    content: `Reports from across multiple towns describe a disturbing trend: children becoming increasingly violent. Reports include throwing rocks at wildlife, chasing chickens with shovels, pushing an elderly woman down stairs, and cornering a stray cat with a brick.\n\nThe behavior is attributed to growing up amid years of wars, bandits, and undead attacks. But some healers and scholars wonder if something more sinister is at work — strange white lights have been seen falling from the sky over Novashan, and animals refuse to produce milk and become agitated.\n\nA previously cheerful elderly beachcomber near South Bay suddenly turned violent, assaulting multiple people before being killed by guards. The pattern of unexplained aggression deepens the mystery.`,
    summary: "Children and elderly turning violent across Novashan. Falling lights from the sky. Animals react with fear. No explanation found.",
    source: "Mystic Quill - June 1022",
    year: 2022, month: 6,
    locations: JSON.stringify(["Novashan", "South Bay"]),
    characters: JSON.stringify([]),
    tags: JSON.stringify(["mystery", "violence", "children", "supernatural", "falling-lights"]),
    category: "story",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ERA 7: THE NOVASHAN-NARRDMYR WAR (~1022–1025 TM)
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "War Erupts Between Novashan and Narrdmyr",
    content: `War breaks out between the Kingdom of Novashan under King Daffyd Belthshazzar and the Kingdom of Narrdmyr under King William Belthshazzar — a dynastic conflict between two branches of the same royal family.\n\nNarrdmyr formalizes military campaigns against Novashani territories. Both kingdoms mobilize their baronial forces for what would become a multi-year war.\n\nThe Mystic Quill reports from the Novashani perspective while the King's Herald provides Narrdmyr's version of events — giving players two sides of every battle.`,
    summary: "War between Novashan (King Daffyd) and Narrdmyr (King William). Dynastic conflict between branches of the Belthshazzar family.",
    source: "Mystic Quill / King's Herald - 1022",
    year: 2022, month: 4,
    locations: JSON.stringify(["Novashan", "Narrdmyr"]),
    characters: JSON.stringify(["King Daffyd Belthshazzar", "King William Belthshazzar"]),
    tags: JSON.stringify(["war", "narrdmyr", "novashan", "dynastic", "belthshazzar"]),
    category: "story",
  },
  {
    title: "Defeat of Blaze Icerose; Spider Sickness Curse",
    content: `The hostile fae entity known as Blaze Icerose is defeated. Two prisoners — Matthew Oats and Ashley Beck — are freed from captivity during the operation.\n\nMeanwhile, a mysterious curse causing spider-related sickness spreads through southeastern Narrdmyr. The magical origins are investigated but no clear source is identified.\n\nSir Korra Stonebrooke is appointed Master of the College of Heralds — a prestigious appointment that recognizes her knowledge of heraldic devices and noble lineage. She would later be promoted to general and die in battle.`,
    summary: "Hostile fae Blaze Icerose defeated. Spider sickness curse in SE Narrdmyr. Sir Korra Stonebrooke appointed Master of Heralds.",
    source: "Mystic Quill - March 1023",
    year: 2023, month: 3,
    locations: JSON.stringify(["Novashan", "Narrdmyr", "College of Heralds"]),
    characters: JSON.stringify(["Blaze Icerose", "Matthew Oats", "Ashley Beck", "Sir Korra Stonebrooke"]),
    tags: JSON.stringify(["fae", "curse", "heraldry", "appointment"]),
    category: "story",
  },
  {
    title: "King Daffyd Goes Missing",
    content: `In the third year of the war, King Daffyd Belthshazzar of Novashan goes missing. Whether he is in hiding, captured, or dead is unknown.\n\nThe disappearance creates political uncertainty and a leadership vacuum during the ongoing war with Narrdmyr. The Council of Barons must govern in his absence.\n\nGiven the Ravensworth revelation about Daffyd's questionable lineage, some whisper that the King left voluntarily — unable to face the truth about his birth. Others fear darker explanations.`,
    summary: "King Daffyd goes missing during the war. Leadership vacuum. Council of Barons governs. Fate unknown.",
    source: "Mystic Quill - August 1024",
    year: 2024, month: 8,
    locations: JSON.stringify(["Novashan"]),
    characters: JSON.stringify(["King Daffyd Belthshazzar"]),
    tags: JSON.stringify(["royalty", "disappearance", "mystery", "succession"]),
    category: "story",
  },
  {
    title: "Narrdmyr Takes Harwick and South Bay",
    content: `Military defeats for Novashan — the strategic locations of Harwick and South Bay fall to Narrdmyr control. The losses represent significant territorial setbacks in the war.\n\nSabotage attacks in Fennor are attributed to the Rising Dawn organization, a shadowy group that becomes a recurring threat.\n\nA mysterious fog cuts off the settlement of Manipathes from outside contact — magical or planar interference suspected. The Temple undergoes reorganization under new leadership: Temple Master Parisa and First Patron Clarence Nahame.`,
    summary: "Narrdmyr captures Harwick and South Bay. Rising Dawn sabotages Fennor. Mysterious fog isolates Manipathes.",
    source: "Mystic Quill - August 1024",
    year: 2024, month: 8,
    locations: JSON.stringify(["Harwick", "South Bay", "Fennor", "Manipathes", "Temple Haven"]),
    characters: JSON.stringify(["Temple Master Parisa", "First Patron Clarence Nahame"]),
    tags: JSON.stringify(["war", "defeat", "rising-dawn", "sabotage", "fog"]),
    category: "story",
  },
  {
    title: "Duchess Morrigan Declares Scotian Sovereignty",
    content: `After years of civil war following Duke MacGregor's execution, Duchess Morrigan MacGregor formally declares Scotia an independent sovereign duchy.\n\nThe Scotian civil war, which began in 1022 as resistance against Duke Callum Duchesne, is resolved. Scotia aligns with Novashan through the political marriage of Bendel Hide and Lily MacGill'Easbaig.\n\nScotia's independence is a major geopolitical shift — a former vassal state now operates as an equal ally. The Narrdmyran forces that had occupied Scotia are forced to retreat.`,
    summary: "Duchess Morrigan declares Scotia independent. Civil war ends. Scotia allies with Novashan through a political marriage.",
    source: "Mystic Quill - September 1024",
    year: 2024, month: 9,
    locations: JSON.stringify(["Scotia"]),
    characters: JSON.stringify(["Duchess Morrigan MacGregor", "Bendel Hide", "Lily MacGill'Easbaig"]),
    tags: JSON.stringify(["independence", "scotia", "sovereignty", "alliance", "marriage"]),
    category: "story",
  },
  {
    title: "Duchy Erin Rebels; Princess Arania Claims Narrdmyr Throne",
    content: `Two explosive political developments shake the war:\n\nDuchy Erin breaks from Novashan and allies with Barony Cherbourg and Princess Arania. This opens a new front in the war and complicates Novashan's military position.\n\nPrincess Arania surfaces publicly, claiming King William attempted to assassinate her. She claims the Narrdmyr throne, creating a succession crisis within Narrdmyr itself.\n\nThe war transforms from a two-sided conflict into a complex multi-faction struggle — Novashan, Narrdmyr, the Erin-Cherbourg-Arania alliance, and independent Scotia all pursue different objectives.`,
    summary: "Duchy Erin rebels from Novashan. Princess Arania claims Narrdmyr throne, says King William tried to kill her. War becomes multi-faction.",
    source: "Mystic Quill - March 1025",
    year: 2025, month: 3,
    locations: JSON.stringify(["Duchy Erin", "Cherbourg", "Narrdmyr"]),
    characters: JSON.stringify(["Princess Arania", "King William Belthshazzar"]),
    tags: JSON.stringify(["rebellion", "succession", "princess", "war", "politics"]),
    category: "story",
  },
  {
    title: "Novashan's Decisive Northern Offensive",
    content: `Novashan launches a devastating multi-pronged offensive against Narrdmyr. Forces attack from three directions:\n\nAusdauer, Ninkatta, and Vin'Ya'Mara from the west. Iomall cavalry from the north. Scotian forces from the east.\n\nThe northern border defenses are dismantled. In a masterful tactical maneuver, Novashan's summer march forces the Narrdmyran army to retreat all the way to the ruins of Maelcor without a major direct battle — achieving bloodless territorial gains through superior positioning.\n\nBaroness Adala of Ninkatta is recognized for her resilience — she has survived three assassination attempts during the campaign.`,
    summary: "Novashan's multi-front offensive breaks Narrdmyr's northern defenses. Enemy retreats to Maelcor without battle. Decisive turning point.",
    source: "Mystic Quill - April/May/June 1025",
    year: 2025, month: 5,
    locations: JSON.stringify(["Northern Border", "Maelcor", "Ausdauer", "Ninkatta", "Vin'Ya'Mara", "Iomall"]),
    characters: JSON.stringify(["Baroness Adala"]),
    tags: JSON.stringify(["war", "offensive", "victory", "strategy", "coalition"]),
    category: "recap",
  },
  {
    title: "Death of Sir Korra Stonebrooke, General of Meraki",
    content: `Sir Korra Stonebrooke, previously Master of the College of Heralds and now general of Barony Meraki's forces, is killed in combat during the northern campaign.\n\nHer body is seized by the enemy, preventing proper burial or resurrection — a devastating blow both militarily and emotionally. Sir Korra had risen from Captain of the Town Watch to general, earning the respect of soldiers and nobles alike.\n\nHer death is followed by questions about war crimes and ethics. An anonymous soldier raises concerns about the conduct of both sides during the campaign.`,
    summary: "General Sir Korra Stonebrooke killed in battle. Body seized by enemy. Questions raised about war crimes.",
    source: "Mystic Quill - May 1025",
    year: 2025, month: 5,
    locations: JSON.stringify(["Northern Battlefield"]),
    characters: JSON.stringify(["Sir Korra Stonebrooke"]),
    tags: JSON.stringify(["death", "war", "general", "meraki", "honor"]),
    category: "obituary",
  },
  {
    title: "Goblin Uprising Destroys Wheat Haven",
    content: `Goblin forces destroy the halfling settlement of Wheat Haven in a devastating assault. Mayor Flap Jack and approximately 30 halflings are killed.\n\nA mysterious magical barrier briefly protected some survivors before failing. Deputy Mayor Petunia Pebbleburrow takes over as interim leader of the shattered community.\n\nThe massacre of a peaceful agricultural settlement — far from the war front — raises fears that the conflict's chaos is empowering opportunistic monster factions to strike undefended communities.`,
    summary: "Goblins destroy halfling settlement Wheat Haven. Mayor Flap Jack and 30 halflings killed. Petunia Pebbleburrow leads survivors.",
    source: "Mystic Quill - May 1025",
    year: 2025, month: 5,
    locations: JSON.stringify(["Wheat Haven"]),
    characters: JSON.stringify(["Mayor Flap Jack", "Petunia Pebbleburrow"]),
    tags: JSON.stringify(["goblins", "massacre", "halflings", "settlement"]),
    category: "story",
  },
  {
    title: "Brisbane Threatens Novashan After Ship Attack",
    content: `Senator Agustus Numitor of the Republic of Tomar/Brisbane issues a "final warning" to Novashan after a Novashani attack on a Brisbane ship.\n\nThe incident threatens to bring a third major power into the already complex war. Baron G'Nip and Countess Felicity undertake a diplomatic mission to Brisbane — now under Tommar occupation — to prevent escalation.\n\nThe prospect of Brisbane entering the war on Narrdmyr's side could tip the balance against Novashan just as its offensive gains momentum.`,
    summary: "Brisbane/Tomar threatens war after Novashan attacks their ship. Baron G'Nip and Countess Felicity sent on diplomatic mission.",
    source: "Mystic Quill - May/August 1025",
    year: 2025, month: 5,
    locations: JSON.stringify(["Brisbane", "Novashan"]),
    characters: JSON.stringify(["Senator Agustus Numitor", "Baron G'Nip", "Countess Felicity"]),
    tags: JSON.stringify(["diplomacy", "brisbane", "tomar", "threat", "war"]),
    category: "story",
  },
  {
    title: "Two Arcane Calamities and Death-Ripples",
    content: `Two catastrophic events shake the realm simultaneously:\n\nTwo massive arcane explosions occur — the first off the coast of New Aladine in Iomall territory, the second inside Ninkatta forest. The cause is unknown.\n\nTwo "death-ripples" emanate from Marwick and Kenet, killing every living thing within a 20-mile radius of each point. The death toll is incalculable.\n\nThese are the most devastating magical events in recorded history. Whether they are connected to the war, to ancient magic, or to something else entirely remains a terrifying mystery. The affected zones become wastelands of death.`,
    summary: "CATASTROPHE: Twin arcane explosions and death-ripples kill everything within 20 miles of Marwick and Kenet. Cause unknown.",
    source: "Mystic Quill - August 1025",
    year: 2025, month: 8,
    locations: JSON.stringify(["New Aladine", "Iomall", "Ninkatta Forest", "Marwick", "Kenet"]),
    characters: JSON.stringify([]),
    tags: JSON.stringify(["catastrophe", "magic", "death", "arcane", "mystery", "mass-extinction"]),
    category: "story",
  },
  {
    title: "Sir Tralik Norwood Found Dead; Baroness Karigan Grieves",
    content: `Sir Tralik Norwood — knight, poet, builder of Temple Haven, co-founder of the Stag and Hound Inn, and overseer of countless construction projects across the Barony — is found dead.\n\nAssassination is suspected. Baroness Karigan of Ausdauer retreats to her chambers upon hearing the news, suggesting a close personal relationship with the slain knight.\n\nSir Tralik's death removes one of the Barony's most beloved figures. Just months earlier, he had composed a moving poem honoring Sir Drayven D'Argentfox. His killer is never identified.`,
    summary: "Sir Tralik Norwood assassinated. Baroness Karigan retreats in grief. The knight, poet, and builder's killer never found.",
    source: "Mystic Quill - August 1025",
    year: 2025, month: 8,
    locations: JSON.stringify(["Ausdauer"]),
    characters: JSON.stringify(["Sir Tralik Norwood", "Baroness Karigan"]),
    tags: JSON.stringify(["assassination", "death", "mystery", "grief"]),
    category: "obituary",
  },
  {
    title: "Surrender Negotiations at Bannor Nogoth",
    content: `Four baronial leaders — Baroness Arra, Baroness Adala, Baron Castien, and Baron Traxx — travel to Bannor Nogoth to negotiate Narrdmyr's surrender.\n\nThe delegation represents Novashan's confidence that the war is nearing its end. However, fighting continues in the southwest where General Bear of Duchy Erin has advanced through central Narrdmyr.\n\nThe ceasefire holds in the north, but Barony Marwood is lost to Erin's forces. The multi-faction nature of the conflict means that even Narrdmyr's surrender may not end the fighting.`,
    summary: "Four barons negotiate Narrdmyr's surrender at Bannor Nogoth. Fighting continues in southwest. War may be ending.",
    source: "Mystic Quill - August 1025",
    year: 2025, month: 8,
    locations: JSON.stringify(["Bannor Nogoth", "Marwood"]),
    characters: JSON.stringify(["Baroness Arra", "Baroness Adala", "Baron Castien", "Baron Traxx", "General Bear"]),
    tags: JSON.stringify(["surrender", "negotiations", "war", "diplomacy", "ceasefire"]),
    category: "story",
  },
  {
    title: "The Voiceless: Silent Horsemen on the Battlefields",
    content: `A new and disturbing presence has been reported across the realm's battlefields: The Voiceless.\n\nSilent horsemen who appear after battles, scavenging from the dead. They do not speak. They do not respond to challenges or hails. Their identity and purpose are completely unknown.\n\nSoldiers report an unsettling feeling in their presence — as if being watched by something that exists between life and death. Whether they are ghosts, a new faction, or something worse, no one can say.`,
    summary: "Silent horsemen called 'The Voiceless' appear on battlefields, scavenging the dead. Identity and purpose unknown.",
    source: "Mystic Quill - July 1025",
    year: 2025, month: 7,
    locations: JSON.stringify(["Battlefields"]),
    characters: JSON.stringify(["The Voiceless"]),
    tags: JSON.stringify(["mystery", "supernatural", "horsemen", "death", "war"]),
    category: "rumor",
  },
  {
    title: "The Weeping Woman of Winter Hart",
    content: `A woman has been seen crying by a river near Winter Hart in Barony Meraki. Those who see her never return.\n\nLocal legends suggest she is a banshee or water spirit — a supernatural entity that lures the unwary to their doom. Barony Meraki, still reeling from the death of General Korra Stonebrooke, adds this supernatural threat to its growing list of concerns.\n\nSimilar reports emerge of a "lake girl" in another location — a young woman who "lives in the water" and lures visitors to a lake. The pattern suggests a widespread supernatural phenomenon rather than an isolated haunting.`,
    summary: "Supernatural woman by river near Winter Hart — those who see her vanish. Similar 'lake girl' reports elsewhere.",
    source: "Mystic Quill - September/November 1025",
    year: 2025, month: 9,
    locations: JSON.stringify(["Winter Hart", "Meraki"]),
    characters: JSON.stringify([]),
    tags: JSON.stringify(["supernatural", "banshee", "water-spirit", "mystery", "disappearance"]),
    category: "rumor",
  },
  {
    title: "A Bard's Tale: Henry Arrives in the Realm",
    content: `A newcomer named Henry chronicles his arrival and first adventures in the realm. Saved by Sir Adriel upon arrival, Henry meets Minstrel Rav'n at the Tea House in Calladagh.\n\nRav'n teaches Henry about magic and introduces him to student Ephemeral. Henry's first adventure takes him into a cave system with Sir Adriel, Sam, and Mochi — fighting hostile dwarves and a stone golem.\n\nHenry's account provides a fresh perspective on the realm through the eyes of someone experiencing it for the first time — the wonder, the danger, and the camaraderie of adventuring life.`,
    summary: "New bard Henry chronicles his first adventures: meeting Minstrel Rav'n, learning magic, and exploring a cave with Sir Adriel.",
    source: "Mystic Quill - June/September 1025",
    year: 2025, month: 6,
    locations: JSON.stringify(["Calladagh", "Tea House"]),
    characters: JSON.stringify(["Henry", "Sir Adriel", "Minstrel Rav'n", "Ephemeral", "Sam", "Mochi"]),
    tags: JSON.stringify(["bard", "adventure", "newcomer", "magic", "cave"]),
    category: "story",
  },
  {
    title: "The Forgotten Road and the Fae Wilds",
    content: `Multiple accounts describe portals to the Fae Wilds — a frozen realm dominated by a massive tree at the edge of mortal understanding.\n\nA courier traveling a road encounters a vanishing inn and village, then delivers a parcel to this frozen land. Another account describes portal travel during the 1022 All-Hallows celebration to the same place.\n\nThe descriptions match: an impossibly large tree in a landscape of eternal frost, guarded by entities that exist outside normal time. The Fae Wilds appear to be growing closer to the mortal realm, with portals becoming more common.\n\nConnected perhaps to the supernatural Bayomal Forest, which has been growing since 1009, the barrier between worlds seems to be thinning.`,
    summary: "Multiple reports of portals to the Fae Wilds: a frozen realm with a massive tree. The barrier between worlds may be thinning.",
    source: "Mystic Quill - September/October 1025",
    year: 2025, month: 10,
    locations: JSON.stringify(["Fae Wilds", "Bayomal Forest"]),
    characters: JSON.stringify([]),
    tags: JSON.stringify(["fae", "portal", "supernatural", "frost", "otherworld"]),
    category: "story",
  },
  {
    title: "The Cave of Meat: Horror at High Haven",
    content: `A massacre at the hamlet of High Haven leads investigators to a nearby cave containing a gruesome discovery — bodies processed as meat.\n\nThe dark and disturbing event represents one of the most horrific crimes in recent memory. Whether the perpetrator is human, monster, or something else is unclear.\n\nHigh Haven, a small community in the western regions, had been peaceful and unremarkable until this discovery. The investigation is ongoing.`,
    summary: "Massacre at High Haven hamlet. Bodies found processed as meat in a nearby cave. Horrific crime, perpetrator unknown.",
    source: "Mystic Quill - August 1025",
    year: 2025, month: 8,
    locations: JSON.stringify(["High Haven"]),
    characters: JSON.stringify([]),
    tags: JSON.stringify(["horror", "massacre", "crime", "mystery"]),
    category: "story",
  },
  {
    title: "Crimson Crows Besiege Wrendale",
    content: `A bandit organization called the Crimson Crows besieges and takes control of the town of Wrendale. Their leader is identified as Valrik "Blood-Wing" Ralthorne, who wears a wolf face.\n\nThe Crimson Crows operate from the Ruins of Char, a fortified position that makes them difficult to dislodge. Their control of Wrendale persists for months, with no military force spared to liberate the town during the ongoing war.\n\nThe Crimson Crows represent a new breed of organized banditry — more like a small army than a criminal gang.`,
    summary: "Crimson Crows under Valrik 'Blood-Wing' Ralthorne seize Wrendale. Operate from the Ruins of Char. Town held for months.",
    source: "Mystic Quill - March/April 1025",
    year: 2025, month: 3,
    locations: JSON.stringify(["Wrendale", "Ruins of Char"]),
    characters: JSON.stringify(["Valrik Blood-Wing Ralthorne"]),
    tags: JSON.stringify(["bandits", "crimson-crows", "siege", "occupation"]),
    category: "story",
  },
  {
    title: "Guild System Established Across the Baronies",
    content: `The guild system is formally established across Baronies Ausdauer, Iomall, and Meraki. A complete Guild Master Registry is published, documenting all guild masters, their guilds, and locations.\n\nNotable appointments include:\n- Capo Grendel (Alchemy, South Bay)\n- Lord Marshal Buliwyf Gregor (Armorsmithing/Metalsmithing/Weaponsmithing, Pelain)\n- Sir Tralik Norwood (Artistry/Carpentry/Masonry, Pelain)\n- Grand Magus Vai Dasha Vittorio (Enchanting, Wyndover)\n- Countess Felicity Ashenwood (Forensics, Riversfork)\n\nGuild administrator Marigold Penner publishes a detailed operations guide explaining guild contracts, renewal processes, and fees.`,
    summary: "Full guild system established across three baronies with published registry. Covers alchemy, smithing, enchanting, and more.",
    source: "Mystic Quill - August 1022 / September 1025",
    year: 2022, month: 8,
    locations: JSON.stringify(["Ausdauer", "Iomall", "Meraki", "Pelain", "Wyndover", "South Bay"]),
    characters: JSON.stringify(["Marigold Penner", "Capo Grendel", "Lord Marshal Buliwyf Gregor", "Sir Tralik Norwood", "Grand Magus Vai Dasha Vittorio", "Countess Felicity Ashenwood"]),
    tags: JSON.stringify(["guilds", "economy", "crafting", "organization", "registry"]),
    category: "announcement",
  },
  {
    title: "Outer Races and the Central Plane",
    content: `A scholarly article explains how Outer Races — beings from beyond the mortal world — draw power from the Central Plane through four mechanisms: Belief, Service, Sacrifice, and Dedication.\n\nThis cosmological framework helps explain many of the supernatural phenomena occurring across the realm: the Fae Wilds growing closer, the death-ripples, the falling lights, and the rise of powerful entities like Demon Lord Lareth.\n\nThe article suggests that mortal actions — war, worship, sacrifice — directly affect the power balance between planes, implying that the multi-year war may be inadvertently strengthening extraplanar threats.`,
    summary: "Scholarly treatise on how Outer Races draw power via Belief, Service, Sacrifice, and Dedication. War may strengthen planar threats.",
    source: "Mystic Quill - September 1025",
    year: 2025, month: 9,
    locations: JSON.stringify(["Central Plane"]),
    characters: JSON.stringify([]),
    tags: JSON.stringify(["cosmology", "magic", "outer-races", "planes", "scholarship"]),
    category: "story",
  },
  {
    title: "Heraldry of the Barony of Ausdauer",
    content: `The Barony of Ausdauer's heraldic crest bears an azure field with an ore embattled line, argent and sable star, cinquefoils, and antlers.\n\nThe motto reads: "Hodie, cras, per vitam, mortem et delorem" — Today, tomorrow, through life, death, and sorrow.\n\nThe crest reflects the barony's mining heritage (ore embattled), its dual nature as both frontier and civilized land (argent/sable), and its connection to the natural world (antlers). The motto captures the resilience of a people who have endured war, famine, and loss but continue forward.`,
    summary: "Detailed blazon of Barony Ausdauer's heraldic crest. Motto: 'Today, tomorrow, through life, death, and sorrow.'",
    source: "Mystic Quill - April 1021",
    year: 2021, month: 4,
    locations: JSON.stringify(["Ausdauer", "Wyndover"]),
    characters: JSON.stringify(["Baron Sir Xandrick von Olanov"]),
    tags: JSON.stringify(["heraldry", "ausdauer", "symbolism", "nobility"]),
    category: "story",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // RECURRING THREADS & MYSTERIES
  // ═══════════════════════════════════════════════════════════════════════════════

  {
    title: "The Toxin Crisis of Novashan",
    content: `A hallucinogenic toxin has created an addiction crisis across Novashan. First reported in 1008, the substance spread rapidly through the population.\n\nBy 1009, children are being found carrying the toxins. The crisis deepens as a boy named Charles in Brenn murders his parents — possibly connected to the substance.\n\nThe source of the toxin is never definitively identified, though some suspect it originates from the same dark forces that would later produce the Crimson Brotherhood. The crisis weakens communities already strained by war and famine.`,
    summary: "Hallucinogenic toxin addiction spreads across Novashan. Children carrying substances. Boy murders parents. Source never found.",
    source: "Mystic Quill - 1008/1009",
    year: 2008, month: 11,
    locations: JSON.stringify(["Novashan", "Brenn"]),
    characters: JSON.stringify(["Charles", "Lapis Lazuli"]),
    tags: JSON.stringify(["toxin", "addiction", "crisis", "crime", "mystery"]),
    category: "story",
  },
  {
    title: "The Fennor Siege and Relief",
    content: `The town of Fennor comes under siege. The water and food supply are compromised by unknown means. Mercenaries are involved in the attack.\n\nSir Nolan and Ylfshae Strongbow lead the defense, holding out until Prince Duncan's cavalry arrives under Sir Reginald of Bren. The siege is lifted, but the damage to the town's infrastructure and morale is severe.\n\nFennor's strategic importance — controlling a key crossroads — makes it a target throughout Novashan's troubled history. The town would be targeted again during the Novashan-Narrdmyr War.`,
    summary: "Fennor besieged — water and food poisoned. Sir Nolan defends until Prince Duncan's cavalry relieves the town.",
    source: "Novashan Quill - July 1008",
    year: 2008, month: 7,
    locations: JSON.stringify(["Fennor"]),
    characters: JSON.stringify(["Sir Nolan", "Ylfshae Strongbow", "Sir Reginald of Bren", "Prince Duncan"]),
    tags: JSON.stringify(["siege", "relief", "fennor", "cavalry"]),
    category: "story",
  },
  {
    title: "Tournament of Midsummer Knights",
    content: `The Tournament of Midsummer Knights in Ilverash crowns individual weapon champions:\n\nZed of Ordu wins spears. Gabriel of House Aladine takes axes. A Battle Mage wins buckler. Tusk fights for the Tuth tribe. Antrell represents House Calladagh.\n\nVarus wins the overall Summer Tournament and is named Summer Champion by Baroness Felicity Ashenwood in a grand ceremony.\n\nThe tournament tradition continues throughout the decades, serving as both entertainment and training for the many wars that follow.`,
    summary: "Midsummer Knights tournament in Ilverash. Varus named Summer Champion. Multiple weapon category winners crowned.",
    source: "Novashan Quill - July 1008",
    year: 2008, month: 7,
    locations: JSON.stringify(["Ilverash"]),
    characters: JSON.stringify(["Varus", "Zed of Ordu", "Gabriel of House Aladine", "Tusk", "Antrell", "Baroness Felicity Ashenwood"]),
    tags: JSON.stringify(["tournament", "combat", "champion", "tradition"]),
    category: "recap",
  },
  {
    title: "The Miloc Elderhart Story: From Squire to Baron",
    content: `Miloc Elderhart's career spans much of Novashan's history. First knighted as Armiger of Prince Duncan in a ceremony called the Night of Atonement in 1008, Miloc would go on to serve the realm through multiple crises.\n\nDuring the 'G' controversy of 1022, Sir Miloc publicly offered to meet the anonymous critic — showing the personal courage that defined his character. He was willing to listen to criticism even when other knights dismissed it.\n\nBy 1025, Miloc has risen to the rank of Baron, praised for his leadership and humility. His journey from squire to baron represents the best of Novashani chivalry.`,
    summary: "Miloc Elderhart's career: knighted in 1008, confronted critic 'G' in 1022, rose to Baron by 1025. Model of chivalry.",
    source: "Multiple Quill Issues - 1008 to 1025",
    year: 2025, month: 6,
    locations: JSON.stringify(["Novashan"]),
    characters: JSON.stringify(["Baron Miloc Elderhart", "Prince Duncan"]),
    tags: JSON.stringify(["knighthood", "career", "chivalry", "leadership"]),
    category: "story",
  },
  {
    title: "Countess Felicity Ashenwood: Decades of Service",
    content: `Countess Felicity Ashenwood is one of the longest-serving nobles in Novashani history. First appearing as Baroness of Autruche in 998, she was elevated to Countess in 1009 during the political reorganization.\n\nShe led the mission to free Duke Mythindor's body from Winterfell, demanded its return in an open letter, and served as Master of Heralds, teacher of heraldic symbology, and cultural patron.\n\nDuring the Novashan-Narrdmyr War, she undertakes a diplomatic mission to Tommar-occupied Brisbane alongside Baron G'Nip. Her decades of service make her one of the realm's most respected figures.`,
    summary: "Countess Felicity Ashenwood: from Baroness (998) to Countess (1009), diplomat, herald, and cultural patron across three decades.",
    source: "Multiple Quill Issues - 998 to 1025",
    year: 2025, month: 9,
    locations: JSON.stringify(["Autruche", "Novashan", "Brisbane"]),
    characters: JSON.stringify(["Countess Felicity Ashenwood"]),
    tags: JSON.stringify(["nobility", "service", "diplomacy", "heraldry", "history"]),
    category: "story",
  },
];
